// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CreateDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateDatabase));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:Ecommerce/Model/Migrations/202104200425560_CreateDB.Designer.cs
            get { return "202104200425560_CreateDB"; }
=======
            get { return "202104230505011_CreateDatabase"; }
>>>>>>> 561ecfe1c531a341a5ab3deb865cc8ef1b8ba277:Ecommerce/Model/Migrations/202104230505011_CreateDatabase.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
